### ISSUE TITLE
PyPi

### ISSUE THREAD

**Issue by scott-w** [adamcupial/django-html5-forms#5]
I've cloned your project and put it up on PyPi under my company's account (pebble). Without realising, I've accidentally put everything up with the html5forms name and your details on.

As soon as you like, I will transfer the ownership of the PyPi package to you, and we will maintain a branch, if necessary.

If you're happy for us to maintain the PyPi package for now, I'll keep it up to date with your repository as best I can.

If you need to contact Pebble, and I'm unavailable on GitHub, then you can send an email to sys.admin at schoolfund.co.uk or use the contact details at the bottom of our company website: https://www.mypebble.co.uk/

**Comment by adamcupial** [comment]
I'm grateful somebody thought of it, you can maintain it ok.
